on: push
jobs:
  build_exe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: nim環境の準備
        run: sudo apt-get install nim

      - name: Windowsへのクロスコンパイル環境
        run: sudo apt-get install mingw-w64

      - name: ディレクトリの移動
        run: cd  ${GITHUB_WORKSPACE}

      - name: コンパイルの実行
        run: nim c -d:mingw hello.nim
      
      - name: 成果物の確認
        run: ls -la
