on: push
jobs:
  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: install choosenim
        run: curl -OL https://github.com/dom96/choosenim/releases/download/v0.6.0/choosenim-0.6.0_windows_amd64.exe
      
      - name: choosenim first install
        run: choosenim-0.6.0_windows_amd64.exe --firstInstall
      
      - name: nimのダウンロード
        run: choosenim-0.6.0_windows_amd64.exe stable

      - name: Nimのバージョン確認
        run: nim -v

      - name: ディレクトリの移動
        run: cd  ${GITHUB_WORKSPACE}

      - name: コンパイルの実行
        run: nim c -d:release hello.nim
      
      - name: 成果物の確認
        run: ls -la
