on: push
jobs:
  build_exe:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: nim環境の準備
        run: scoop install nim

      - name: Nimのバージョン確認
        run: nim -v

      - name: ディレクトリの移動
        run: cd  ${GITHUB_WORKSPACE}

      - name: コンパイルの実行
        run: nim c -d:release hello.nim
      
      - name: 成果物の確認
        run: ls -la
